#!/usr/bin/env python3
"""Generate a monthly tracking report from collected repo and paper stats.

Reads previously fetched stats (from fetch_repo_stats.py and
fetch_paper_citations.py) and produces a Markdown summary report.

Usage:
    python generate_report.py --month 2026-03 [--output report_2026-03.md]
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


TRACKER_DIR = Path(__file__).resolve().parent.parent
REPO_STATS_FILE = TRACKER_DIR / "repo_stats.json"
CITATION_STATS_FILE = TRACKER_DIR / "citation_stats.json"


def load_json(path: Path) -> list[dict[str, Any]]:
    """Load a JSON stats file, returning an empty list if not found."""
    if not path.exists():
        print(f"WARNING: {path} not found. Run the fetch scripts first.")
        return []
    with open(path, "r") as f:
        return json.load(f)


def generate_repo_table(repo_stats: list[dict[str, Any]]) -> str:
    """Generate a Markdown table of repository statistics."""
    if not repo_stats:
        return "*No repository stats available. Run `fetch_repo_stats.py` first.*\n"

    lines = [
        "| Repository | Stars | Forks | Open Issues | Latest Release | Last Push |",
        "|---|---|---|---|---|---|",
    ]
    for entry in repo_stats:
        info = entry.get("info", {})
        release = entry.get("latest_release")
        repo_name = entry.get("repo", "unknown")
        stars = info.get("stars", "N/A")
        forks = info.get("forks", "N/A")
        issues = info.get("open_issues", "N/A")
        release_tag = release.get("tag", "N/A") if release else "N/A"
        last_push = info.get("last_push", "N/A")
        if last_push and last_push != "N/A":
            last_push = last_push[:10]  # date only

        lines.append(
            f"| [{repo_name}](https://github.com/{repo_name}) "
            f"| {stars} | {forks} | {issues} | {release_tag} | {last_push} |"
        )

    return "\n".join(lines) + "\n"


def generate_citation_table(citation_stats: list[dict[str, Any]]) -> str:
    """Generate a Markdown table of paper citation statistics."""
    if not citation_stats:
        return "*No citation stats available. Run `fetch_paper_citations.py` first.*\n"

    lines = [
        "| Paper | Year | Category | Citations | Influential |",
        "|---|---|---|---|---|",
    ]
    sorted_papers = sorted(
        citation_stats,
        key=lambda x: x.get("citation_count") or 0,
        reverse=True,
    )
    for entry in sorted_papers:
        title = entry.get("title", "Unknown")
        year = entry.get("year", "N/A")
        category = entry.get("category", "N/A")
        citations = entry.get("citation_count", "N/A")
        influential = entry.get("influential_citations", "N/A")
        lines.append(f"| {title} | {year} | {category} | {citations} | {influential} |")

    return "\n".join(lines) + "\n"


def generate_report(month: str, repo_stats: list, citation_stats: list) -> str:
    """Generate the full Markdown report.

    Args:
        month: Report month in YYYY-MM format.
        repo_stats: Repository statistics data.
        citation_stats: Paper citation data.

    Returns:
        Complete Markdown report as a string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# Segmentation Tracker Monthly Report - {month}

> Generated on {now}

## Repository Statistics

{generate_repo_table(repo_stats)}

## Paper Citation Statistics

{generate_citation_table(citation_stats)}

## Summary

- **Repositories tracked**: {len(repo_stats)}
- **Papers tracked**: {len(citation_stats)}

## Notes

- Star and fork counts are snapshots at the time of fetching.
- Citation counts sourced from Semantic Scholar Academic Graph API.
- Influential citations are those identified by Semantic Scholar as
  having a significant impact on the citing paper.

---
*Report generated by `generate_report.py`*
"""
    return report


def main():
    parser = argparse.ArgumentParser(description="Generate monthly tracking report")
    parser.add_argument(
        "--month", "-m",
        type=str,
        required=True,
        help="Report month in YYYY-MM format (e.g. 2026-03)",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=None,
        help="Output Markdown file (default: report_YYYY-MM.md)",
    )
    args = parser.parse_args()

    output_path = args.output or TRACKER_DIR / f"report_{args.month}.md"

    repo_stats = load_json(REPO_STATS_FILE)
    citation_stats = load_json(CITATION_STATS_FILE)

    report = generate_report(args.month, repo_stats, citation_stats)

    with open(output_path, "w") as f:
        f.write(report)

    print(f"Report written to {output_path}")


if __name__ == "__main__":
    main()
