#!/usr/bin/env python3
"""Auto-generate a table of contents for the Segmentation Archive.

Scans the archive directory structure and generates a Markdown table
of contents listing all sections, subdirectories, and files.

Usage:
    python scripts/generate_toc.py [--output TABLE_OF_CONTENTS.md]
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

ARCHIVE_ROOT = Path(__file__).resolve().parent.parent

# Directories to skip when generating the TOC
SKIP_DIRS = {
    ".git",
    "__pycache__",
    ".streamlit",
    "node_modules",
    ".cache",
    ".search_index",
    ".venv",
    "venv",
}

# File patterns to skip
SKIP_PATTERNS = {
    ".gitkeep",
    ".DS_Store",
    "Thumbs.db",
}


def should_skip(path: Path) -> bool:
    """Check if a path should be skipped in the TOC.

    Args:
        path: File or directory path.

    Returns:
        True if the path should be excluded from the TOC.
    """
    if path.name in SKIP_DIRS or path.name in SKIP_PATTERNS:
        return True
    if path.name.startswith(".") and path.name != ".streamlit":
        return True
    return False


def build_tree(root: Path, prefix: str = "", is_last: bool = True) -> list[str]:
    """Build a tree representation of the directory structure.

    Args:
        root: Current directory to process.
        prefix: Indentation prefix for the current level.
        is_last: Whether this is the last item at the current level.

    Returns:
        List of formatted tree lines.
    """
    lines = []

    children = sorted(
        [c for c in root.iterdir() if not should_skip(c)],
        key=lambda p: (not p.is_dir(), p.name.lower()),
    )

    for i, child in enumerate(children):
        is_child_last = i == len(children) - 1
        connector = "└── " if is_child_last else "├── "
        extension = "    " if is_child_last else "│   "

        if child.is_dir():
            lines.append(f"{prefix}{connector}{child.name}/")
            lines.extend(
                build_tree(child, prefix + extension, is_child_last)
            )
        else:
            lines.append(f"{prefix}{connector}{child.name}")

    return lines


def generate_section_summary(root: Path) -> list[dict]:
    """Generate a summary of each top-level section.

    Args:
        root: Archive root directory.

    Returns:
        List of section info dicts with name, file_count, and description.
    """
    sections = []

    for child in sorted(root.iterdir()):
        if not child.is_dir() or should_skip(child):
            continue

        file_count = sum(1 for _ in child.rglob("*") if _.is_file() and not should_skip(_))

        # Try to read description from README.md
        readme = child / "README.md"
        description = ""
        if readme.exists():
            try:
                text = readme.read_text(encoding="utf-8")
                for line in text.split("\n"):
                    line = line.strip()
                    if line and not line.startswith("#") and not line.startswith("---"):
                        description = line[:100]
                        break
            except Exception:
                pass

        sections.append({
            "name": child.name,
            "file_count": file_count,
            "description": description,
        })

    return sections


def generate_toc(root: Path) -> str:
    """Generate the full table of contents as Markdown.

    Args:
        root: Archive root directory.

    Returns:
        Complete Markdown TOC as a string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    sections = generate_section_summary(root)
    tree_lines = build_tree(root)

    # Build section summary table
    section_table = "| Section | Files | Description |\n|---|---|---|\n"
    for sec in sections:
        section_table += f"| `{sec['name']}` | {sec['file_count']} | {sec['description']} |\n"

    toc = f"""# Segmentation Archive - Table of Contents

> Auto-generated on {now}

## Section Summary

{section_table}

## Directory Tree

```
{root.name}/
{chr(10).join(tree_lines)}
```

---
*Generated by `scripts/generate_toc.py`*
"""
    return toc


def main():
    parser = argparse.ArgumentParser(
        description="Generate table of contents for the Segmentation Archive"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=ARCHIVE_ROOT / "TABLE_OF_CONTENTS.md",
        help="Output file path",
    )
    parser.add_argument(
        "--archive-root",
        type=Path,
        default=ARCHIVE_ROOT,
        help="Archive root directory",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of file",
    )
    args = parser.parse_args()

    toc = generate_toc(args.archive_root)

    if args.stdout:
        print(toc)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(toc)
        print(f"Table of contents written to {args.output}")


if __name__ == "__main__":
    main()
